Commissar Regiment Selection
Daelso/Warhammer-IS12 pull request #179
Opened 2021-08-20 20:19 UTC by Max-023

Gives Commissars access to a regiment selection. Available regiments are Cadians (same uniform), Kriegers, and Catachans. Removes the Commissar mask from the office, as well as the chainsword (Catachan Comm gets it).

2021-08-20 23:13 UTC, EliteRiceFarmer requested changes

2021-08-20 23:13 UTC, EliteRiceFarmer commented on code/modules/clothing/shoes/jobs.dm
> +	name = "boots of the commissar"
Commissariat Boots

2021-08-20 23:21 UTC, EliteRiceFarmer requested changes

2021-08-20 23:21 UTC, EliteRiceFarmer commented on code/modules/clothing/shoes/jobs.dm
> +	name = "boots of the commissar"
```suggestion
	name = "Commissariat Service Boots"
```

2021-08-20 23:21 UTC, EliteRiceFarmer commented on code/modules/clothing/shoes/jobs.dm
> +	desc = "Knee high riding boots of an officer of the Officio Prefectus."
```suggestion
	desc = "Service Boots issued to Commissar of the Officio Prefectus."
```

2021-08-20 23:21 UTC, EliteRiceFarmer commented on code/modules/clothing/suits/armor.dm
> +	desc = "The Commissar's magnificent, charismatic that strikes dreads and fears into the mind of lowly Imperial Guardsmen and heretics alike. Plated in Caraspace, giving it much more protection than
```suggestion
	desc = "The Krieg Commissar's Trenchcoat, Worn and damaged by flame of war, Plated in Caraspace for extra protection and decorated in Krieg style, golden-lining span across the coat, Recreating the Emperor's Light."
```

2021-08-20 23:21 UTC, EliteRiceFarmer commented on code/modules/clothing/under/jobs/security.dm
> +	name = "krieg Battle Uniform"
```suggestion
	name = "Commissariat Dress Uniform"
```

2021-08-20 23:21 UTC, EliteRiceFarmer commented on code/modules/clothing/under/jobs/security.dm
> +	desc = "What was once a full green uniform has been stripped down for survivability on the inhospitable world of catachan, though now it just seems like a power move to wear this on a frozen tundra.
```suggestion
	desc = "Under the rigorous trenchcoat of an Commissar is his neatly made service uniform, featuring his nametag and medals on their set of collar dress shirt and service pants."
```

2021-08-20 23:21 UTC, EliteRiceFarmer commented on code/modules/clothing/under/jobs/security.dm
> +	desc = "What was once a full green uniform has been stripped down for survivability on the inhospitable world of catachan, though now it just seems like a power move to wear this on a frozen tundra.
I don't know if this is for catachan only or for all commissar. If not, don't merge.

We also need undershirt for normal commissar as well, so make one if you can.

2021-08-21 05:23 UTC, closed without merging

2021-08-21 05:24 UTC, Max-023 commented
closing due to revisions in the discord